version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: plataforma_educativa_db
    environment:
      POSTGRES_DB: plataforma_educativa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: plataforma_educativa_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
